### ISSUE TITLE
Add "programming blogs" category

### ISSUE THREAD

**Issue by Ari24-cb24** [themorpheustutorials/resources#9]
Gibt einige Blogs zu Programmiersprachen, glaube, dass die meisten medium oder real-python kennen.

Wäre ganz praktisch auch solch eine Kategorie zu haben

**Comment by felbinger** [comment]
Einfach selbst in der `mkdocs.yml` zur Navigation hinzufügen und einen Ordner `programming` oder so erstellen.

**Comment by Ari24-cb24** [comment]
Gut zu wissen
